### ISSUE TITLE
Kanban board set up.

### ISSUE THREAD

**Issue by AlexRS90** [AlexRS90/recipe-app#12]
For this activity, we created a new kanban project from scratch adding the tasks for the recipes app project. We are a team of two and the members are @codepantherr and @AlexRS90 

Here is a link to our kanban board ⬇️ 
https://github.com/users/AlexRS90/projects/1

**Comment by julie-ify** [comment]
Hi @AlexRS90 and @codepantherr, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has `error code: 404 "page not found"`. I checked your Github `Projects` and there is no project created. Kindly create your project and submit for review.

<img width="840" alt="chrome_C09TsLxTFK" src="https://user-images.githubusercontent.com/81468675/157081009-a022b503-406c-4ca3-8c53-a73018c0ffaf.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AlexRS90** [comment]
Hello, @julie-ify thanks for the feedback I don't notice that the project's visibility was private now is public. I'll request a new review. 🚀
